### ISSUE TITLE
Version of Unity

### ISSUE THREAD

**Issue by mokun** [Zulban/martian-agora#1]
Hi @Zulban,

What minimum of version of Unity3D is required for your project ?

-mokun

**Comment by Zulban** [comment]
For Unity projects you can find this information in ProjectVersion.txt:

https://github.com/Zulban/martian-agora/blob/master/ProjectSettings/ProjectVersion.txt

In this case it is "2017.2.0xb6Linux". To open the project for the first time on Windows, you may need to change the contents of this file to say just "2017.2.0xb6". Also, just an "upgrade" using this as a minimum version should work too.

Cheers

**Comment by Zulban** [comment]
Hey, were you able to get the project running? Let me know if you need any other help.
